### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by arjung24** [mbahArip/next-gdrive-index#1]
How to deploy brother. Where is the guideline?

**Comment by mbahArip** [comment]
Hello, I'm sorry but there's currently still no setup guide since I'm still changing things.

But if you want to deploy it now, you can follow this step:
- Fork this repository
- Follow [this step](https://github.com/mbahArip/next-gdrive-index/blob/main/public/setup/GoogleCloudStep.md) to get your own client_id, client_secret, and refresh_token
- Open [this stackblitz project](https://stackblitz.com/edit/next-gdrive-index-generate-passkey?file=index.js) to generate your own encryption key

- Add client_id to `src/api.config.js`
- Add client_secret, refresh_token, and encryption key to your `environment variable`

Your `environment variable` should be look like this
```
DRIVE_CLIENT_SECRET: your client_secret
DRIVE_REFRESH_TOKEN: your refresh_token
NEXT_PUBLIC_DOMAIN: deployment domain
NEXT_PUBLIC_ENCRYPTION_KEY: your encryption key
```

**Comment by arjung24** [comment]
Ohh great. Thanks a lot Brother 🤗🤗
