### ISSUE TITLE
This Serverless Function has timed out

### ISSUE THREAD

**Issue by mioscape** [mbahArip/next-gdrive-index#11]
Somehow non-video file can't downloaded

```GET

/api/download/dba3fa04b0c37ca49527e0825bd0c7259d385356e39c77c0ce88a738cf835a89d9a6a8795db1307c3cdd1fa9305e9f16

xxx
Task timed out after 10.02 seconds
```

Downloading .apk file:
![downloading .apk file](https://github.com/mbahArip/next-gdrive-index/assets/43681888/12d9a02c-6b87-462a-a9ef-3dda6c008b67)

Also I'm wondering why the copy link & download link feature, give Vercel deployment link instead of registered domain?

**Comment by mbahArip** [comment]
How big is the APK file? and make sure to select the closest function region on vercel project settings.

Seems like I forgot to swap the position of the base path.
You can change the base path on config, and swap the environment. (also make sure you have set `NEXT_PUBLIC_DOMAIN` on your environment)

**Comment by mioscape** [comment]
80mb~ size. Okay I'll try it

**Comment by mbahArip** [comment]
Weird, it should've redirect the user to google drive download link if the size is larger than `maxFileSize` (4MB by default).
Just making sure, but you've already set the root folder sharing options to `Anyone with link` right?

I'll try to replicate this on my side.

**Comment by mioscape** [comment]
Yes, I did. 
![Screenshot_20240412-051958_Drive](https://github.com/mbahArip/next-gdrive-index/assets/43681888/e298c256-741c-45dc-86c6-50657e3dc988)

**Comment by mbahArip** [comment]
Ah, looks like it's missing `size` field from file metadata, and causing the endpoint to download the whole file instead of redirecting it (this causing the timeout error since it would take more than 10s).

I've pushed the fix on `v2` branch, since I'm still working on another thing, I won't merge it to main branch at least until weekend.  
But you can check what I've changed [here](https://github.com/mbahArip/next-gdrive-index/commit/c5434fe9c415db33567e9923ca397ab86c17a127#diff-f827d62ec481ed392fa2ba788bbf6a506fc6008724bbb173e2be62044693b63fR54), and update your own fork.

**Comment by mioscape** [comment]
Thank you very much🎉

**Comment by mbahArip** [comment]
@hctofu86 

Masalahnya di [config](https://github.com/hctofu86/next-gdrive-index/blob/70c1d4421a47e9759cf8de149145c03b46f970c8/src/config/gIndex.config.ts#L191)

Vercel cuman support direct download up sampe 4MB doang, jadi maxFileSize harus diset ke 4MB.
Biar kl file size diatas 4MB, download pake link dari google drivenya
