### ISSUE TITLE
'403 Forbidden' on file previews beyond file size limits

### ISSUE THREAD

**Issue by TenSeventy7** [mbahArip/next-gdrive-index#16]
I'm having issues getting file previews working for files beyond the file limit I've set. I have it deployed on Netlify so it's up to 6MB, but files that go beyond it fail to preview.
![image](https://github.com/mbahArip/next-gdrive-index/assets/28522823/7c694282-d968-4ff9-98d7-736568975b6f)

The file gets successfully downloaded though, either by clicking Download or generating a download link and using that.

This is the network request the app does when it loads the preview; Drive returns a 401.

![image](https://github.com/mbahArip/next-gdrive-index/assets/28522823/82873127-d035-40ff-87d8-79088664d58f)

They're not exactly 'sensitive' files (and I'm meaning to make it a public files archive for my stuff so here is the website):

~~https://silph.tenseventyseven.xyz/~~

https://bill.tenseventyseven.xyz/

**Comment by TenSeventy7** [comment]
From what I've noticed, using the Download or download links have Cookies in them (presumably Google cookies as part of the browser?) while the preview doesn't have them.

**Comment by mbahArip** [comment]
Just realize now it won't preview anything above the size limit.
I'll try to resolve this tomorrow.

**Comment by mbahArip** [comment]
S, yeah, it's Cookies problem.
Google Drive web content link need some cookies that are marked as `secure` and `httpOnly`, and neither route handler nor set the source directly fix the problem.

But, I can still get the image preview working by using the large sized thumbnail, but I don't think I can get the other preview working if the size is higher than the max file size.
I'll push the fix for this next week.

**Comment by mbahArip** [comment]
You can reopen / create a new issue if you have problem with the new update. 🍺
