### ISSUE TITLE
Show shortcut/linked file(?)

### ISSUE THREAD

**Issue by mioscape** [mbahArip/next-gdrive-index#18]
Somehow, such a hassle to updating readme.md per-folder.
I wonder, Does shortcut/linked file could be displayed on index?

![image](https://github.com/mbahArip/next-gdrive-index/assets/43681888/72d1fb7f-0da3-4336-a5f8-616e9ebd84aa)

**Comment by mbahArip** [comment]
It should be possible, but let me try it first.
If it's doable, it will be added on the next update

**Comment by mbahArip** [comment]
It is possible, but it might be a little bit slower than actual file.
Since it needs 2 API request
- Get the `.readme.md` file, either if it's the actual file or shortcut
- If it's shortcut, get the actual file content then send to the user

Will be added on next PR

![image](https://github.com/mbahArip/next-gdrive-index/assets/62494292/4cf5dd6f-aabc-49db-80d9-4927abc374cc)
![image](https://github.com/mbahArip/next-gdrive-index/assets/62494292/17662bea-7851-4760-a138-eba95e36e6e2)

**Comment by mioscape** [comment]
Should make it configurable then, if it's make the app little bit slower

**Comment by mbahArip** [comment]
Don't think need a new config, since it only add like 20 - 100ms
