### ISSUE TITLE
Cloudflare deploy

### ISSUE THREAD

**Issue by hctofu86** [mbahArip/next-gdrive-index#19]
Apa bisa dideploy ke Cloudflare pages?

**Comment by mbahArip** [comment]
Belum pernah dicoba gan
Harusnya tinggal ganti runtime doang ke edge di tiap page / api routes
Tapi bisa aja error gara2 ada library yg ga support sama edge

**Comment by exenee** [comment]
I tried to deploy to cloudflare with specifying edge in the API routes. This ended up resulting in `Module not found: Can't resolve 'https', 'http', 'net'`. I also tried opennextjs/cloudflare and that gave me `ReferenceError: crypto is not defined`. Not sure where to go from here and I've been troubleshooting for 3 hours. This is really annoying as on Vercel and other deployment services the initial caching of file lists takes a lot longer compared to CloudFlare.

**Comment by mbahArip** [comment]
> I tried to deploy to cloudflare with specifying edge in the API routes. This ended up resulting in `Module not found: Can't resolve 'https', 'http', 'net'`. I also tried opennextjs/cloudflare and that gave me `ReferenceError: crypto is not defined`. Not sure where to go from here and I've been troubleshooting for 3 hours. This is really annoying as on Vercel and other deployment services the initial caching of file lists takes a lot longer compared to CloudFlare.

The `https`, `http`, and `net` error are caused by `googleapis`.
There are [alternative solution for this](https://github.com/googleapis/google-api-nodejs-client/issues/3453), using fetch call instead using `googleapis` (which mean scrape all googleapis stuff, implement token request, and replace it with fetch)

and for the `crypto` error, tbh I don't know why it doesn't work since I'm using [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) and when I test it locally it runs without any problem on edge runtime
