### ISSUE TITLE
Feat: Support Shared-Drive

### ISSUE THREAD

**Issue by loadingthedev** [mbahArip/next-gdrive-index#3]
Hi @mbahArip ,
Thanks for this awesome project. really like how it works and how u handles all download logic and all.

only one little complain that your repo didn't support for Shared-drive(Teamdrive)
so i am working on the support team drive feature.
[Link](https://github.com/loadingthedev/next-gdrive-index/tree/support-shared-drive) to my fork

**Comment by loadingthedev** [comment]
if you have any input on my implentation.
please feel free to point me.

**Comment by mbahArip** [comment]
Hello, thank you for the implementation.

Because I don't have team / shared drive, can you make sure it's working properly on the shared drive? (Search, read, view, or download the file)
Since this project using service account to access the drive API, I just want to make sure it can read the content of the shared drive.

**Comment by loadingthedev** [comment]
Yes, I already implemented the list all files from the shared drive.

I will make sure that all the features work for team drive as well.
